// <auto-generated />
using System;
using Geny.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Geny.Infrastructure.Migrations
{
    [DbContext(typeof(GenyDbContext))]
    [Migration("20260903091506_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Geny.Domain.Entities.Badge", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("BadgeType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("badge_type");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "BadgeType");

                    b.ToTable("badges", (string)null);
                });

            modelBuilder.Entity("Geny.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Geny.Domain.Entities.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ShareToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShareToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("collections", (string)null);
                });

            modelBuilder.Entity("Geny.Domain.Entities.CollectionFact", b =>
                {
                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CollectionId", "FactId");

                    b.HasIndex("FactId");

                    b.ToTable("collection_facts", (string)null);
                });

            modelBuilder.Entity("Geny.Domain.Entities.DailyEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContextText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FactId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsLive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("PercentCorrectGuess")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("TotalReactions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventDate")
                        .IsUnique();

                    b.HasIndex("FactId");

                    b.ToTable("daily_events", (string)null);
                });

            modelBuilder.Entity("Geny.Domain.Entities.EventReaction", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DailyEventId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("GuessedBeforeReveal")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ReactedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reaction_type");

                    b.Property<bool>("SharedToday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("UserId", "DailyEventId");

                    b.HasIndex("DailyEventId");

                    b.ToTable("event_reactions", (string)null);
                });

            modelBuilder.Entity("Geny.Domain.Entities.Fact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CalendarDate")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("HookSentence")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Level1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level3")
                        .HasColumnType("text");

                    b.Property<string>("NarrativeHint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CalendarDate");

                    b.HasIndex("CategoryId");

                    b.ToTable("facts", (string)null);
                });

            modelBuilder.Entity("Geny.Domain.Entities.IntellectualProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("BreadthScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("CuriosityScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("LastCalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviousTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProfileTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RetentionScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.PrimitiveCollection<string>("TopCategories")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("WeeklyInsight")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("UserId");

                    b.ToTable("intellectual_profiles", (string)null);
                });

            modelBuilder.Entity("Geny.Domain.Entities.LiveEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<int>("ParticipantCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.PrimitiveCollection<string>("QuestionIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WinnerId");

                    b.ToTable("live_events", (string)null);
                });

            modelBuilder.Entity("Geny.Domain.Entities.LiveEventAnswer", b =>
                {
                    b.Property<Guid>("LiveEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("AnsweredAtMs")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("PointsEarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("LiveEventId", "UserId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("live_event_answers", (string)null);
                });

            modelBuilder.Entity("Geny.Domain.Entities.LiveEventParticipant", b =>
                {
                    b.Property<Guid>("LiveEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("FinalRank")
                        .HasColumnType("integer");

                    b.Property<int>("FinalScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("XpAwarded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("LiveEventId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("live_event_participants", (string)null);
                });

            modelBuilder.Entity("Geny.Domain.Entities.NarrativeThread", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string>("FactIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExclusive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("narrative_threads", (string)null);
                });

            modelBuilder.Entity("Geny.Domain.Entities.NotificationSetting", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DailyFactEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<TimeOnly>("DailyFactTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time without time zone")
                        .HasDefaultValue(new TimeOnly(8, 0, 0));

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("LiveEventReminderEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PushToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("StreakReminderEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("notification_settings", (string)null);
                });

            modelBuilder.Entity("Geny.Domain.Entities.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FactId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string>("WrongAnswers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("XpReward")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(25);

                    b.HasKey("Id");

                    b.HasIndex("FactId")
                        .IsUnique();

                    b.ToTable("quiz_questions", (string)null);
                });

            modelBuilder.Entity("Geny.Domain.Entities.SocialFeedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FactId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LiveEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ThreadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FactId");

                    b.HasIndex("LiveEventId");

                    b.HasIndex("ThreadId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("social_feed_items", (string)null);
                });

            modelBuilder.Entity("Geny.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultMood")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("mixed");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsPro")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProfilePublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string>("PreferredCategories")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ProExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalXp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Geny.Domain.Entities.UserNarrativeProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NarrativeThreadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentPosition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "NarrativeThreadId");

                    b.HasIndex("NarrativeThreadId");

                    b.ToTable("user_narrative_progresses", (string)null);
                });

            modelBuilder.Entity("Geny.Domain.Entities.UserProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FactId")
                        .HasColumnType("uuid");

                    b.Property<int>("DepthReached")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NextReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("QuizAnswered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool?>("QuizCorrect")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TimeSpentSec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("UserId", "FactId");

                    b.HasIndex("FactId");

                    b.ToTable("user_progresses", (string)null);
                });

            modelBuilder.Entity("Geny.Domain.Entities.UserReferral", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InviteeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InviterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferralToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("XpAwarded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("InviteeId");

                    b.HasIndex("InviterId");

                    b.HasIndex("ReferralToken")
                        .IsUnique();

                    b.ToTable("user_referrals", (string)null);
                });

            modelBuilder.Entity("Geny.Domain.Entities.Badge", b =>
                {
                    b.HasOne("Geny.Domain.Entities.User", "User")
                        .WithMany("Badges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Geny.Domain.Entities.Collection", b =>
                {
                    b.HasOne("Geny.Domain.Entities.User", "User")
                        .WithMany("Collections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Geny.Domain.Entities.CollectionFact", b =>
                {
                    b.HasOne("Geny.Domain.Entities.Collection", "Collection")
                        .WithMany("CollectionFacts")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Geny.Domain.Entities.Fact", "Fact")
                        .WithMany("CollectionFacts")
                        .HasForeignKey("FactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Fact");
                });

            modelBuilder.Entity("Geny.Domain.Entities.DailyEvent", b =>
                {
                    b.HasOne("Geny.Domain.Entities.Fact", "Fact")
                        .WithMany("DailyEvents")
                        .HasForeignKey("FactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fact");
                });

            modelBuilder.Entity("Geny.Domain.Entities.EventReaction", b =>
                {
                    b.HasOne("Geny.Domain.Entities.DailyEvent", "DailyEvent")
                        .WithMany("EventReactions")
                        .HasForeignKey("DailyEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Geny.Domain.Entities.User", "User")
                        .WithMany("EventReactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Geny.Domain.Entities.Fact", b =>
                {
                    b.HasOne("Geny.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Geny.Domain.Entities.IntellectualProfile", b =>
                {
                    b.HasOne("Geny.Domain.Entities.User", "User")
                        .WithOne("IntellectualProfile")
                        .HasForeignKey("Geny.Domain.Entities.IntellectualProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Geny.Domain.Entities.LiveEvent", b =>
                {
                    b.HasOne("Geny.Domain.Entities.User", "Winner")
                        .WithMany("WonLiveEvents")
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("Geny.Domain.Entities.LiveEventAnswer", b =>
                {
                    b.HasOne("Geny.Domain.Entities.LiveEvent", "LiveEvent")
                        .WithMany("Answers")
                        .HasForeignKey("LiveEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Geny.Domain.Entities.QuizQuestion", "Question")
                        .WithMany("LiveEventAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Geny.Domain.Entities.User", "User")
                        .WithMany("LiveEventAnswers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LiveEvent");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Geny.Domain.Entities.LiveEventParticipant", b =>
                {
                    b.HasOne("Geny.Domain.Entities.LiveEvent", "LiveEvent")
                        .WithMany("Participants")
                        .HasForeignKey("LiveEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Geny.Domain.Entities.User", "User")
                        .WithMany("LiveEventParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LiveEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Geny.Domain.Entities.NarrativeThread", b =>
                {
                    b.HasOne("Geny.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Geny.Domain.Entities.NotificationSetting", b =>
                {
                    b.HasOne("Geny.Domain.Entities.User", "User")
                        .WithOne("NotificationSetting")
                        .HasForeignKey("Geny.Domain.Entities.NotificationSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Geny.Domain.Entities.QuizQuestion", b =>
                {
                    b.HasOne("Geny.Domain.Entities.Fact", "Fact")
                        .WithOne("QuizQuestion")
                        .HasForeignKey("Geny.Domain.Entities.QuizQuestion", "FactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fact");
                });

            modelBuilder.Entity("Geny.Domain.Entities.SocialFeedItem", b =>
                {
                    b.HasOne("Geny.Domain.Entities.Fact", "Fact")
                        .WithMany("SocialFeedItems")
                        .HasForeignKey("FactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Geny.Domain.Entities.LiveEvent", "LiveEvent")
                        .WithMany("SocialFeedItems")
                        .HasForeignKey("LiveEventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Geny.Domain.Entities.NarrativeThread", "NarrativeThread")
                        .WithMany("SocialFeedItems")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Geny.Domain.Entities.User", "User")
                        .WithMany("SocialFeedItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fact");

                    b.Navigation("LiveEvent");

                    b.Navigation("NarrativeThread");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Geny.Domain.Entities.UserNarrativeProgress", b =>
                {
                    b.HasOne("Geny.Domain.Entities.NarrativeThread", "NarrativeThread")
                        .WithMany("UserProgresses")
                        .HasForeignKey("NarrativeThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Geny.Domain.Entities.User", "User")
                        .WithMany("NarrativeProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NarrativeThread");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Geny.Domain.Entities.UserProgress", b =>
                {
                    b.HasOne("Geny.Domain.Entities.Fact", "Fact")
                        .WithMany("UserProgresses")
                        .HasForeignKey("FactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Geny.Domain.Entities.User", "User")
                        .WithMany("UserProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fact");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Geny.Domain.Entities.UserReferral", b =>
                {
                    b.HasOne("Geny.Domain.Entities.User", "Invitee")
                        .WithMany("ReceivedReferrals")
                        .HasForeignKey("InviteeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Geny.Domain.Entities.User", "Inviter")
                        .WithMany("SentReferrals")
                        .HasForeignKey("InviterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invitee");

                    b.Navigation("Inviter");
                });

            modelBuilder.Entity("Geny.Domain.Entities.Collection", b =>
                {
                    b.Navigation("CollectionFacts");
                });

            modelBuilder.Entity("Geny.Domain.Entities.DailyEvent", b =>
                {
                    b.Navigation("EventReactions");
                });

            modelBuilder.Entity("Geny.Domain.Entities.Fact", b =>
                {
                    b.Navigation("CollectionFacts");

                    b.Navigation("DailyEvents");

                    b.Navigation("QuizQuestion");

                    b.Navigation("SocialFeedItems");

                    b.Navigation("UserProgresses");
                });

            modelBuilder.Entity("Geny.Domain.Entities.LiveEvent", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Participants");

                    b.Navigation("SocialFeedItems");
                });

            modelBuilder.Entity("Geny.Domain.Entities.NarrativeThread", b =>
                {
                    b.Navigation("SocialFeedItems");

                    b.Navigation("UserProgresses");
                });

            modelBuilder.Entity("Geny.Domain.Entities.QuizQuestion", b =>
                {
                    b.Navigation("LiveEventAnswers");
                });

            modelBuilder.Entity("Geny.Domain.Entities.User", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("Collections");

                    b.Navigation("EventReactions");

                    b.Navigation("IntellectualProfile");

                    b.Navigation("LiveEventAnswers");

                    b.Navigation("LiveEventParticipations");

                    b.Navigation("NarrativeProgresses");

                    b.Navigation("NotificationSetting");

                    b.Navigation("ReceivedReferrals");

                    b.Navigation("SentReferrals");

                    b.Navigation("SocialFeedItems");

                    b.Navigation("UserProgresses");

                    b.Navigation("WonLiveEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
